[General]
UpstreamHost = 127.0.0.1
UpstreamPort = 3883
BindAddress =
ListenPort = 3884
MainloopRate = 240
UpstreamUpdateRate = 120

[Tracker uav1]
Upstream = uav1
Downstream = uav1
Sensors = 1

[Tracker ugv1]
Upstream = ugv1
Downstream = ugv1
Sensors = 1
